### ISSUE TITLE
i can't get it working

### ISSUE THREAD

**Issue by ngangchill** [CI-Craftsman/CLI#1]
i'm trying to set it up in my windows . 
i followed your installation steps .composer installation is ok but php bin/craftsman is not working.

bin/craftsman filecontains

```    
    #!/usr/bin/env sh

dir=$(d=${0%[/\\]*}; cd "$d"; cd "../vendor/craftsman/cli" && pwd)

# See if we are running in Cygwin by checking for cygpath program
if command -v 'cygpath' >/dev/null 2>&1; then
	# Cygwin paths start with /cygdrive/ which will break windows PHP,
	# so we need to translate the dir path to windows format. However
	# we could be using cygwin PHP which does not require this, so we
	# test if the path to PHP starts with /cygdrive/ rather than /usr/bin
	if [[ $(which php) == /cygdrive/* ]]; then
		dir=$(cygpath -m "$dir");
	fi
fi

dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/craftsman" "$@"
````
Im newbee, help me..

**Comment by davidsosavaldes** [comment]
Could you please give us more details about this error? (the console output, the env variables, the OS version, etc)

**Comment by ngangchill** [comment]
i followed https://ci-craftsman.github.io/documentation/installation/

Config the bin-dir path inside your composer.json file:
"config": {
    "bin-dir": "bin"
}
Next, install the package with composer:
composer require craftsman/cli
Install the environment variables:
cp path/to/vendor/craftsman/cli/.craftsman.example .craftsman
If you configure the bin directory you can run the command like this:
php bin/craftsman


but when i try  
    php bin/craftsman

it shows

     #!/usr/bin/env sh

     dir=$(d=${0%[/\\]*}; cd "$d"; cd "../vendor/nikic/php-parser/bin" && pwd)

     # See if we are running in Cygwin by checking for cygpath program
     if command -v 'cygpath' >/dev/null 2>&1; then
	     # Cygwin paths start with /cygdrive/ which will break windows PHP,
	     # so we need to translate the dir path to windows format. However
	     # we could be using cygwin PHP which does not require this, so we
	     # test if the path to PHP starts with /cygdrive/ rather than /usr/bin
	     if [[ $(which php) == /cygdrive/* ]]; then
	     	dir=$(cygpath -m "$dir");
	     fi
     fi

     dir=$(echo $dir | sed 's/ /\ /g')
     "${dir}/php-parse" "$@"



My os: windows 8.1,

local server   UwAmp 
php  5.6.28

with git bash

**Comment by davidsosavaldes** [comment]
What's the output when you run the command like this:

`php vendor/bin/craftsman`

**Comment by ngangchill** [comment]
same as above..

**Comment by ngangchill** [comment]
it is showing the contents of the craftsman file in the terminal.
 every file in bin folder  [craftsman,php-parse,psysh] has same content that view in the terminal as i write above.

**Comment by ngangchill** [comment]
now i tried in laravel homestead-7, result is same


i think problem in dir path
        
vendor/bin/craftsman: 
        #!/usr/bin/env sh

        dir=$(d=${0%[/\\]*}; cd "$d"; cd "../d11wtq/boris/bin" && pwd)
         Cygwin paths start with /cygdrive/ which will break windows PHP,
	# so we need to translate the dir path to windows format.

dir path

**Comment by davidsosavaldes** [comment]
Try without php and use windows separators:

`vendor\bin\craftsman`

**Comment by ngangchill** [comment]
Thank you so much.. its working with "vendor/bin/craftsman" on homestead-7

**Comment by davidsosavaldes** [comment]
Excelent, i will include this indication on documentation for future releases. 

Thanks to you for your report.

**Comment by ngangchill** [comment]
Thats great...

welcome & again thanks for your help.... :+1:
